<h1><center><font color='red'>RED ZONE</font></center></h1>

<div class="alert alert-warning">
<b>Step 1:</b> Importing the dependencies
</div>

In [1]:
#Importing the dependencies
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

<div class="alert alert-warning">
<b>Step 2:</b> Loading the csv file
</div>

In [2]:
#Loading the csv file
df = pd.read_csv('hepatitis.csv', encoding = 'utf8')
df.head()

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,32.059452,female,no,yes,yes,yes,yes,yes,no,no,no,no,no,1.000000,48.365665,51.718598,4.182311,74.038508,no,LIVE
1,41.229532,female,no,no,no,no,no,yes,no,no,no,no,no,1.146760,63.522251,29.216549,4.030845,25.462303,no,LIVE
2,62.133896,female,yes,no,no,no,no,yes,no,no,no,no,no,1.000000,44.055037,42.183894,4.865354,36.232554,no,LIVE
3,48.209988,female,yes,no,yes,no,no,yes,no,yes,yes,no,no,0.669207,131.126032,50.817332,3.902101,42.755563,yes,DIE
4,32.699629,female,yes,no,yes,yes,yes,no,yes,no,yes,no,no,1.000000,123.179908,20.318702,4.075779,42.079171,no,LIVE

<div class="alert alert-warning">
<b>Step 3:</b> Changing the "Yes" / "No" to 1's and 0's
</div>

In [3]:
#Changing the "YES"/"No" to 1/0 for the neceassary columns
df['STEROID'] = df['STEROID'].map({'yes' : 1, 'no' : 0})
df['ANTIVIRALS'] = df['ANTIVIRALS'].map({'yes' : 1, 'no' : 0})
df['FATIGUE'] = df['FATIGUE'].map({'yes' : 1, 'no' : 0})
df['MALAISE'] = df['MALAISE'].map({'yes' : 1, 'no' : 0})
df['ANOREXIA'] = df['ANOREXIA'].map({'yes' : 1, 'no' : 0})

df['LIVER_BIG'] = df['LIVER_BIG'].map({'yes' : 1, 'no' : 0})
df['LIVER_FIRM'] = df['LIVER_FIRM'].map({'yes' : 1, 'no' : 0})
df['SPLEEN_PALPABLE'] = df['SPLEEN_PALPABLE'].map({'yes' : 1, 'no' : 0})
df['SPIDERS'] = df['SPIDERS'].map({'yes' : 1, 'no' : 0})
df['ASCITES'] = df['ASCITES'].map({'yes' : 1, 'no' : 0})

df['VARICES'] = df['VARICES'].map({'yes' : 1, 'no' : 0})
df['HISTOLOGY'] = df['HISTOLOGY'].map({'yes' : 1, 'no' : 0})
df['SEX'] = df['SEX'].map({'male' : 1, 'female' : 0})
df['Class'] = df['Class'].map({'LIVE' : 1, 'DIE' : 0})

In [4]:
df.head()

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,32.059452,0,0,1,1,1,1,1,0,0,0,0,0,1.000000,48.365665,51.718598,4.182311,74.038508,0,1
1,41.229532,0,0,0,0,0,0,1,0,0,0,0,0,1.146760,63.522251,29.216549,4.030845,25.462303,0,1
2,62.133896,0,1,0,0,0,0,1,0,0,0,0,0,1.000000,44.055037,42.183894,4.865354,36.232554,0,1
3,48.209988,0,1,0,1,0,0,1,0,1,1,0,0,0.669207,131.126032,50.817332,3.902101,42.755563,1,0
4,32.699629,0,1,0,1,1,1,0,1,0,1,0,0,1.000000,123.179908,20.318702,4.075779,42.079171,0,1

<div class="alert alert-warning">
<b>Step 4:</b> Splitting the data into X and Y, for Train - Test Split
</div>

In [ ]:
X = df.drop("Class", axis=1)
y = df["Class"]
print(X.shape, y.shape)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical
from sklearn.svm import SVC 

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)

model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

(1000000, 19) (1000000,)

Using TensorFlow backend.

In [45]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

TypeError: 'tuple' object is not callable

<div class="alert alert-warning">
<b>Step 5:</b> Creating deep learning layers
</div>

<div class="alert alert-warning">
<b>Step 6:</b> Compiling and fitting the model
</div>