<h1><center><font color='red'>RED ZONE</font></center></h1>

<div class="alert alert-warning">
<b>Step 1:</b> Importing the dependencies
</div>

In [2]:
#Importing the dependencies
import pandas as pd
import sklearn

<div class="alert alert-warning">
<b>Step 2:</b> Loading the csv file
</div>

In [32]:
#Loading the csv file
df = pd.read_csv('hepatitis.csv', encoding = 'utf8')
df.head()

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,32.059452,female,no,yes,yes,yes,yes,yes,no,no,no,no,no,1.000000,48.365665,51.718598,4.182311,74.038508,no,LIVE
1,41.229532,female,no,no,no,no,no,yes,no,no,no,no,no,1.146760,63.522251,29.216549,4.030845,25.462303,no,LIVE
2,62.133896,female,yes,no,no,no,no,yes,no,no,no,no,no,1.000000,44.055037,42.183894,4.865354,36.232554,no,LIVE
3,48.209988,female,yes,no,yes,no,no,yes,no,yes,yes,no,no,0.669207,131.126032,50.817332,3.902101,42.755563,yes,DIE
4,32.699629,female,yes,no,yes,yes,yes,no,yes,no,yes,no,no,1.000000,123.179908,20.318702,4.075779,42.079171,no,LIVE

<div class="alert alert-warning">
<b>Step 3:</b> Changing the "Yes" / "No" to 1's and 0's
</div>

In [33]:
#Changing the "YES"/"No" to 1/0 for the neceassary columns
df['STEROID'] = df['STEROID'].map({'yes' : 1, 'no' : 0})
df['ANTIVIRALS'] = df['ANTIVIRALS'].map({'yes' : 1, 'no' : 0})
df['FATIGUE'] = df['FATIGUE'].map({'yes' : 1, 'no' : 0})
df['MALAISE'] = df['MALAISE'].map({'yes' : 1, 'no' : 0})
df['ANOREXIA'] = df['ANOREXIA'].map({'yes' : 1, 'no' : 0})

df['LIVER_BIG'] = df['LIVER_BIG'].map({'yes' : 1, 'no' : 0})
df['LIVER_FIRM'] = df['LIVER_FIRM'].map({'yes' : 1, 'no' : 0})
df['SPLEEN_PALPABLE'] = df['SPLEEN_PALPABLE'].map({'yes' : 1, 'no' : 0})
df['SPIDERS'] = df['SPIDERS'].map({'yes' : 1, 'no' : 0})
df['ASCITES'] = df['ASCITES'].map({'yes' : 1, 'no' : 0})

df['VARICES'] = df['VARICES'].map({'yes' : 1, 'no' : 0})
df['HISTOLOGY'] = df['HISTOLOGY'].map({'yes' : 1, 'no' : 0})
df['SEX'] = df['SEX'].map({'male' : 1, 'female' : 0})
df['Class'] = df['Class'].map({'LIVE' : 1, 'DIE' : 0})

In [34]:
df.head()

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,32.059452,0,0,1,1,1,1,1,0,0,0,0,0,1.000000,48.365665,51.718598,4.182311,74.038508,0,1
1,41.229532,0,0,0,0,0,0,1,0,0,0,0,0,1.146760,63.522251,29.216549,4.030845,25.462303,0,1
2,62.133896,0,1,0,0,0,0,1,0,0,0,0,0,1.000000,44.055037,42.183894,4.865354,36.232554,0,1
3,48.209988,0,1,0,1,0,0,1,0,1,1,0,0,0.669207,131.126032,50.817332,3.902101,42.755563,1,0
4,32.699629,0,1,0,1,1,1,0,1,0,1,0,0,1.000000,123.179908,20.318702,4.075779,42.079171,0,1

<div class="alert alert-warning">
<b>Step 4:</b> Splitting the data into X and Y, for Train - Test Split
</div>

In [38]:
X = df.drop("Class", axis=1)
y = df["Class"]
print(X.shape, y.shape)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)

X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

(1000000, 19) (1000000,)

C:\Users\kraag\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\kraag\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\ipykernel\__main__.py:13: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
C:\Users\kraag\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\ipykernel\__main__.py:14: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.

<div class="alert alert-warning">
<b>Step 5:</b> Creating deep learning layers
</div>

In [39]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=19))
model.add(Dense(units=1, activation='softmax'))

<div class="alert alert-warning">
<b>Step 6:</b> Compiling and fitting the model
</div>

In [41]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train,
    y_train,
    epochs=60,
    shuffle=True,
    verbose=2
)

Epoch 1/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 2/60
 - 25s - loss: 3.3131 - acc: 0.7922
Epoch 3/60
 - 21s - loss: 3.3131 - acc: 0.7922
Epoch 4/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 5/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 6/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 7/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 8/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 9/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 10/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 11/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 12/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 13/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 14/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 15/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 16/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 17/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 18/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 19/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 20/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 21/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 22/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 23/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 24/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 25/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 26/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 27/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 28/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 29/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 30/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 31/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 32/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 33/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 34/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 35/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 36/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 37/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 38/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 39/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 40/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 41/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 42/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 43/60
 - 21s - loss: 3.3131 - acc: 0.7922
Epoch 44/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 45/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 46/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 47/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 48/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 49/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 50/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 51/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 52/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 53/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 54/60
 - 19s - loss: 3.3131 - acc: 0.7922
Epoch 55/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 56/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 57/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 58/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 59/60
 - 20s - loss: 3.3131 - acc: 0.7922
Epoch 60/60
 - 20s - loss: 3.3131 - acc: 0.7922

In [44]:
encoded_predictions = model.predict_classes(X_test_scaled[:5])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\kraag\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:273: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [46]:
prediction_labels

array([1, 1, 1, 1, 1], dtype=int64)